export const LOAD_CHARACTERS_REQUEST = 'LOAD_CHARACTERS_REQUEST';
export const LOAD_CHARACTERS_SUCCESS = 'LOAD_CHARACTERS_SUCCESS';
export const LOAD_CHARACTERS_ERROR = 'LOAD_CHARACTERS_ERROR';

export const LOAD_CHARACTER_REQUEST = 'LOAD_CHARACTER_REQUEST';
export const LOAD_CHARACTER_SUCCESS = 'LOAD_CHARACTER_SUCCESS';
export const LOAD_CHARACTER_ERROR = 'LOAD_CHARACTER_ERROR';

export const LOAD_CHARACTER_HOMEWORLD_REQUEST = 'LOAD_CHARACTER_HOMEWORLD_REQUEST';
export const LOAD_CHARACTER_HOMEWORLD_SUCCESS = 'LOAD_CHARACTER_HOMEWORLD_SUCCESS';
export const LOAD_CHARACTER_HOMEWORLD_ERROR = 'LOAD_CHARACTER_HOMEWORLD_ERROR';

export const ADD_CHARACTER_COMMENT = 'ADD_CHARACTER_COMMENT';

export const UPVOTE_CHARACTER = 'UPVOTE_CHARACTER';
export const DOWNVOTE_CHARACTER = 'DOWNVOTE_CHARACTER';
