const API = {
  TOURNAMENT_ENDPOINT: '/tournament',
  TEAM_ENDPOINT: '/team',
  MATCH_SCORE_ENDPOINT: '/match',
  WINNER_ENDPOINT: '/winner'
}

const TOURNAMENT = {
  FIRST_ROUND: 0,
  MATCH_COMPLETED: 'MATCH_COMPLETED',
  NEW_TOURNAMENT: 'NEW_TOURNAMENT',
  TOURNAMENT_COMPLETED: 'TOURNAMENT_COMPLETED'
};

const EMOJIS = {
  PENDING_MATCH_SYMBOL: 'emoji-hand',
  COMPLETED_MATCH_SYMBOL: 'emoji-punch',
}
